sudo: required
language: node_js

services:
  - docker

before_install:
  # login
  - echo "$ DOCKER_PASSWORD" | docker login -u "$ DOCKER_USERNAME" --password-stdin

script:
  # run tests
  - docker-compose -f docker-compose.test.yml up
