version: '3.7'
services:
  graphql:
    build:
      context: ./
      target: base
    volumes:
      - ./node_modules:/app/node_modules
      - ./:/app
    command: npm start
    ports:
      - "4000:4000"
    expose:
      - 4000
    environment:
      PORT: "4000"

