version: '3.7'
services:
  graphql:
    build:
      context: ./
      target: base
    volumes:
      - ./node_modules:/app/node_modules
      - ./:/app
    command: npm test
    environment:
      CI: "true"

