version: '3.7'
services:
  graphql:
    build:
      context: ./
      target: base
    image: server:test
    volumes:
      - ./src:/app/src
    command: "npm test -- /app/src/"
    environment:
      CI: "true"

